costmap:
  costmap:
    ros__parameters:
      footprint_padding: 0.2
      update_frequency: 20.0
      publish_frequency: 20.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.5 # radius set and used, so no footprint points
      resolution: 0.1
      rolling_window: true
      # plugins: ["obstacle_layer", "voxel_layer"]
      # plugins: ["obstacle_layer", "inflation_layer"]
      # plugins: ["obstacle_layer","denoise_layer"]
      plugins: ["obstacle_layer","denoise_layer", "static_layer",'inflation_layer']
      height: 12
      width: 12
      # initial_transform_timeout: 1000
      # track_unknown_space: True
      track_unknown_space: False
      trinary_costmap: True 
      unknown_cost_value: 255
      use_maximum: False
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        # observation_sources: pointcloud
        footprint_clearing_enabled: False
        max_obstacle_height: 2.0
        combination_method: 1
        # pointcloud:  # no frame set, uses frame from message
        #   topic: /ouster/points
        #   max_obstacle_height: 2.0
        #   min_obstacle_height: 0.0
        #   obstacle_max_range: 10.0
        #   obstacle_min_range: 0.0
        #   raytrace_max_range: 10.0
        #   raytrace_min_range: 0.0
        #   clearing: True
        #   marking: True
        #   data_type: "PointCloud2"
        scan:
          topic: /scan
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 3.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: True
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0    
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:  # no frame set, uses frame from message
          topic: /ouster/points
          max_obstacle_height: 2.0
          min_obstacle_height: 0.55
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        # inflation_radius: 0.125
        inflation_radius: 0.4
        cost_scaling_factor: 0.0
        inflate_unknown: false
        inflate_around_unknown: false
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: false
        minimal_group_size: 3
        group_connectivity_type: 8

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: false
        subscribe_to_updates: true
        transform_tolerance: 0.1
      always_send_full_costmap: True


# local_costmap:
#   local_costmap:
#     ros__parameters:
#       update_frequency: 5.0
#       publish_frequency: 2.0
#       global_frame: odom
#       robot_base_frame: base_link
#       use_sim_time: False
#       rolling_window: true
#       width: 3
#       height: 3
#       resolution: 0.05
map_server:
  map_server:
    ros__parameters:
      use_sim_time: True
      frame_id: "odom"

# map_saver:
#   ros__parameters:
#     use_sim_time: False
#     save_map_timeout: 5.0
#     free_thresh_default: 0.25
#     occupied_thresh_default: 0.65
#     map_subscribe_transient_local: True
